#!/bin/bash

# mine a block, so nodes don't get stuck waiting to sync
./run-bitcoin-cli generate 1

sleep 1

# connect client and server
./run-lncli-client connect 0234e910d973dced9eb6c4d17454f62abc7a45c0841e429c64a3ac19a00ad5d028@localhost:9737
